import Head from 'next/head';
import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { updateNumber } from '../redux/actions/demoSlice';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [num, updateNum] = useState(0);
  const { number } = useSelector((state) => state.demo);
  const dispatch = useDispatch();
  const updateNumberInStore = () => {
    dispatch(updateNumber({ number: num }));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl text-[#0070f3] text-center my-4">
        NEXT TEMPLATE
      </div>
      <div className="flex flex-col">
        <input
          className="border-2 border-gray-900 bg-white px-2 py-1 text-black self-start"
          type="number"
          name="number"
          id="number"
          value={num}
          onChange={(e) => updateNum(e.target.value)}
        />
        <button
          className="bg-blue-500 px-2 py-1 my-4 rounded-lg self-start"
          onClick={updateNumberInStore}
        >
          update number in Store
        </button>
        <p>Current Value of number in Store: {number}</p>
      </div>
    </div>
  );
}
